/*
 * Telstra Messaging API
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telstra.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.telstra.models.Status;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OutboundPollResponse
 */

public class OutboundPollResponse {
  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private String to;

  public static final String SERIALIZED_NAME_SENT_TIMESTAMP = "sentTimestamp";
  @SerializedName(SERIALIZED_NAME_SENT_TIMESTAMP)
  private String sentTimestamp;

  public static final String SERIALIZED_NAME_RECEIVED_TIMESTAMP = "receivedTimestamp";
  @SerializedName(SERIALIZED_NAME_RECEIVED_TIMESTAMP)
  private String receivedTimestamp;

  public static final String SERIALIZED_NAME_DELIVERY_STATUS = "deliveryStatus";
  @SerializedName(SERIALIZED_NAME_DELIVERY_STATUS)
  private Status deliveryStatus;


  public OutboundPollResponse to(String to) {
    
    this.to = to;
    return this;
  }

   /**
   * The phone number (recipient) the message was sent to (in E.164 format). 
   * @return to
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "+61418123456", value = "The phone number (recipient) the message was sent to (in E.164 format). ")

  public String getTo() {
    return to;
  }


  public void setTo(String to) {
    this.to = to;
  }


  public OutboundPollResponse sentTimestamp(String sentTimestamp) {
    
    this.sentTimestamp = sentTimestamp;
    return this;
  }

   /**
   * The date and time when the message was sent.
   * @return sentTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2017-03-17T09:16:49+10:00", value = "The date and time when the message was sent.")

  public String getSentTimestamp() {
    return sentTimestamp;
  }


  public void setSentTimestamp(String sentTimestamp) {
    this.sentTimestamp = sentTimestamp;
  }


  public OutboundPollResponse receivedTimestamp(String receivedTimestamp) {
    
    this.receivedTimestamp = receivedTimestamp;
    return this;
  }

   /**
   * The date and time when the message was recieved by recipient.
   * @return receivedTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2017-03-17T09:16:50+10:00", value = "The date and time when the message was recieved by recipient.")

  public String getReceivedTimestamp() {
    return receivedTimestamp;
  }


  public void setReceivedTimestamp(String receivedTimestamp) {
    this.receivedTimestamp = receivedTimestamp;
  }


  public OutboundPollResponse deliveryStatus(Status deliveryStatus) {
    
    this.deliveryStatus = deliveryStatus;
    return this;
  }

   /**
   * Get deliveryStatus
   * @return deliveryStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Status getDeliveryStatus() {
    return deliveryStatus;
  }


  public void setDeliveryStatus(Status deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutboundPollResponse outboundPollResponse = (OutboundPollResponse) o;
    return Objects.equals(this.to, outboundPollResponse.to) &&
        Objects.equals(this.sentTimestamp, outboundPollResponse.sentTimestamp) &&
        Objects.equals(this.receivedTimestamp, outboundPollResponse.receivedTimestamp) &&
        Objects.equals(this.deliveryStatus, outboundPollResponse.deliveryStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, sentTimestamp, receivedTimestamp, deliveryStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutboundPollResponse {\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    sentTimestamp: ").append(toIndentedString(sentTimestamp)).append("\n");
    sb.append("    receivedTimestamp: ").append(toIndentedString(receivedTimestamp)).append("\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

