/*
 * Telstra Messaging API
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telstra.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ProvisionNumberResponse
 */

public class ProvisionNumberResponse {
  public static final String SERIALIZED_NAME_DESTINATION_ADDRESS = "destinationAddress";
  @SerializedName(SERIALIZED_NAME_DESTINATION_ADDRESS)
  private String destinationAddress;

  public static final String SERIALIZED_NAME_EXPIRY_DATE = "expiryDate";
  @SerializedName(SERIALIZED_NAME_EXPIRY_DATE)
  private BigDecimal expiryDate;


  public ProvisionNumberResponse destinationAddress(String destinationAddress) {
    
    this.destinationAddress = destinationAddress;
    return this;
  }

   /**
   * The mobile phone number that was allocated
   * @return destinationAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "+61412345678", value = "The mobile phone number that was allocated")

  public String getDestinationAddress() {
    return destinationAddress;
  }


  public void setDestinationAddress(String destinationAddress) {
    this.destinationAddress = destinationAddress;
  }


  public ProvisionNumberResponse expiryDate(BigDecimal expiryDate) {
    
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Free Trial apps can only add activeDays for their provisioned number every 30 days. This is in Unix time format.
   * @return expiryDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1534463077362", value = "Free Trial apps can only add activeDays for their provisioned number every 30 days. This is in Unix time format.")

  public BigDecimal getExpiryDate() {
    return expiryDate;
  }


  public void setExpiryDate(BigDecimal expiryDate) {
    this.expiryDate = expiryDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProvisionNumberResponse provisionNumberResponse = (ProvisionNumberResponse) o;
    return Objects.equals(this.destinationAddress, provisionNumberResponse.destinationAddress) &&
        Objects.equals(this.expiryDate, provisionNumberResponse.expiryDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationAddress, expiryDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProvisionNumberResponse {\n");
    sb.append("    destinationAddress: ").append(toIndentedString(destinationAddress)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

