/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi.models;

import java.util.*;

public class ErrorErrorBuilder {
    //the instance to build
    private ErrorError errorError;

    /**
     * Default constructor to initialize the instance
     */
    public ErrorErrorBuilder() {
        errorError = new ErrorError();
    }

    /**
     * A short error code
     */
    public ErrorErrorBuilder status(String status) {
        errorError.setStatus(status);
        return this;
    }

    /**
     * Message describing the error.
     */
    public ErrorErrorBuilder message(String message) {
        errorError.setMessage(message);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ErrorError build() {
        return errorError;
    }
}