/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi.models;

import java.util.*;

public class InboundPollResponseBuilder {
    //the instance to build
    private InboundPollResponse inboundPollResponse;

    /**
     * Default constructor to initialize the instance
     */
    public InboundPollResponseBuilder() {
        inboundPollResponse = new InboundPollResponse();
    }

    /**
     * The phone number (recipient) that the message was sent to(in
     * E.164 format).
     */
    public InboundPollResponseBuilder destinationAddress(String destinationAddress) {
        inboundPollResponse.setDestinationAddress(destinationAddress);
        return this;
    }

    /**
     * The phone number (sender) that the message was sent from (in
     * E.164 format).
     */
    public InboundPollResponseBuilder senderAddress(String senderAddress) {
        inboundPollResponse.setSenderAddress(senderAddress);
        return this;
    }

    /**
     * Text body of the message that was sent
     */
    public InboundPollResponseBuilder message(String message) {
        inboundPollResponse.setMessage(message);
        return this;
    }

    /**
     * The date and time when the message was recieved by recipient.
     */
    public InboundPollResponseBuilder sentTimestamp(String sentTimestamp) {
        inboundPollResponse.setSentTimestamp(sentTimestamp);
        return this;
    }

    /**
     * Optional message ID of the SMS you sent. Use this ID to viewthe message status or get responses.
     */
    public InboundPollResponseBuilder messageId(String messageId) {
        inboundPollResponse.setMessageId(messageId);
        return this;
    }

    /**
     * Message status from the server
     */
    public InboundPollResponseBuilder status(String status) {
        inboundPollResponse.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InboundPollResponse build() {
        return inboundPollResponse;
    }
}