/*
 * Telstra Messaging API
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.telstra.messaging;

import com.telstra.ApiException;
import com.telstra.messaging.InboundPollResponse;
import com.telstra.messaging.MessageSentResponse;
import com.telstra.messaging.OutboundPollResponse;
import com.telstra.messaging.SendMmsRequest;
import com.telstra.messaging.SendSMSRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MessagingApi
 */
@Ignore
public class MessagingApiTest {

    private final MessagingApi api = new MessagingApi();

    
    /**
     * Get MMS Status
     *
     * Get MMS Status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMMSStatusTest() throws ApiException {
        String messageid = null;
        OutboundPollResponse response = api.getMMSStatus(messageid);

        // TODO: test validations
    }
    
    /**
     * Get SMS Status
     *
     * Get Message Status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSMSStatusTest() throws ApiException {
        String messageId = null;
        OutboundPollResponse response = api.getSMSStatus(messageId);

        // TODO: test validations
    }
    
    /**
     * Retrieve SMS Responses
     *
     * Retrieve Messages
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveSMSResponsesTest() throws ApiException {
        List<InboundPollResponse> response = api.retrieveSMSResponses();

        // TODO: test validations
    }
    
    /**
     * Send MMS
     *
     * Send MMS
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendMMSTest() throws ApiException {
        SendMmsRequest body = null;
        Object response = api.sendMMS(body);

        // TODO: test validations
    }
    
    /**
     * Send SMS
     *
     * Send Message
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendSMSTest() throws ApiException {
        SendSMSRequest payload = null;
        MessageSentResponse response = api.sendSMS(payload);

        // TODO: test validations
    }
    
}
