/*
 * Telstra Messaging API
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telstra.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InboundPollResponse
 */
public class InboundPollResponseTest {
    private final InboundPollResponse model = new InboundPollResponse();

    /**
     * Model tests for InboundPollResponse
     */
    @Test
    public void testInboundPollResponse() {
        // TODO: test InboundPollResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'destinationAddress'
     */
    @Test
    public void destinationAddressTest() {
        // TODO: test destinationAddress
    }

    /**
     * Test the property 'senderAddress'
     */
    @Test
    public void senderAddressTest() {
        // TODO: test senderAddress
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'messageId'
     */
    @Test
    public void messageIdTest() {
        // TODO: test messageId
    }

    /**
     * Test the property 'sentTimestamp'
     */
    @Test
    public void sentTimestampTest() {
        // TODO: test sentTimestamp
    }

}
