/*
 * Telstra Messaging API
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telstra.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.telstra.models.Status;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OutboundPollResponse
 */
public class OutboundPollResponseTest {
    private final OutboundPollResponse model = new OutboundPollResponse();

    /**
     * Model tests for OutboundPollResponse
     */
    @Test
    public void testOutboundPollResponse() {
        // TODO: test OutboundPollResponse
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'sentTimestamp'
     */
    @Test
    public void sentTimestampTest() {
        // TODO: test sentTimestamp
    }

    /**
     * Test the property 'receivedTimestamp'
     */
    @Test
    public void receivedTimestampTest() {
        // TODO: test receivedTimestamp
    }

    /**
     * Test the property 'deliveryStatus'
     */
    @Test
    public void deliveryStatusTest() {
        // TODO: test deliveryStatus
    }

}
