/*
 * Telstra Messaging API
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telstra.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProvisionNumberRequest
 */
public class ProvisionNumberRequestTest {
    private final ProvisionNumberRequest model = new ProvisionNumberRequest();

    /**
     * Model tests for ProvisionNumberRequest
     */
    @Test
    public void testProvisionNumberRequest() {
        // TODO: test ProvisionNumberRequest
    }

    /**
     * Test the property 'activeDays'
     */
    @Test
    public void activeDaysTest() {
        // TODO: test activeDays
    }

    /**
     * Test the property 'notifyURL'
     */
    @Test
    public void notifyURLTest() {
        // TODO: test notifyURL
    }

}
