/*
 * Messaging API v3.1.0
 * Send and receive SMS & MMS programmatically, leveraging Australia's leading mobile network. With Telstra's Messaging API, we take out the complexity to allow seamless messaging integration into your app, with just a few lines of code. Our REST API is enterprise grade, allowing you to communicate with engaging SMS & MMS messaging in your web and mobile apps in near real-time on a global scale. 
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telstra;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;
import org.threeten.bp.LocalDate;
/**
 * GetReports200ResponseReportsInner
 */


public class GetReports200ResponseReportsInner {
  @SerializedName("reportId")
  private UUID reportId = null;

  @SerializedName("reportStatus")
  private String reportStatus = null;

  @SerializedName("reportType")
  private String reportType = null;

  @SerializedName("reportExpiry")
  private LocalDate reportExpiry = null;

  public GetReports200ResponseReportsInner reportId(UUID reportId) {
    this.reportId = reportId;
    return this;
  }

   /**
   * Use this UUID to fetch your report with the GET /reports/{reportId} endpoint. 
   * @return reportId
  **/
  @Schema(description = "Use this UUID to fetch your report with the GET /reports/{reportId} endpoint. ")
  public UUID getReportId() {
    return reportId;
  }

  public void setReportId(UUID reportId) {
    this.reportId = reportId;
  }

  public GetReports200ResponseReportsInner reportStatus(String reportStatus) {
    this.reportStatus = reportStatus;
    return this;
  }

   /**
   * The status of the report. It will be either:        * **queued** – the report is in the queue for generation.        * **completed** – the report is ready for download.        * **failed** – the report failed to generate. Please try again. 
   * @return reportStatus
  **/
  @Schema(description = "The status of the report. It will be either:        * **queued** – the report is in the queue for generation.        * **completed** – the report is ready for download.        * **failed** – the report failed to generate. Please try again. ")
  public String getReportStatus() {
    return reportStatus;
  }

  public void setReportStatus(String reportStatus) {
    this.reportStatus = reportStatus;
  }

  public GetReports200ResponseReportsInner reportType(String reportType) {
    this.reportType = reportType;
    return this;
  }

   /**
   * The type of report generated.
   * @return reportType
  **/
  @Schema(description = "The type of report generated.")
  public String getReportType() {
    return reportType;
  }

  public void setReportType(String reportType) {
    this.reportType = reportType;
  }

  public GetReports200ResponseReportsInner reportExpiry(LocalDate reportExpiry) {
    this.reportExpiry = reportExpiry;
    return this;
  }

   /**
   * The expiry date of your report. After this date, you will be unable to download your report. 
   * @return reportExpiry
  **/
  @Schema(description = "The expiry date of your report. After this date, you will be unable to download your report. ")
  public LocalDate getReportExpiry() {
    return reportExpiry;
  }

  public void setReportExpiry(LocalDate reportExpiry) {
    this.reportExpiry = reportExpiry;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetReports200ResponseReportsInner inlineResponse2004Reports = (GetReports200ResponseReportsInner) o;
    return Objects.equals(this.reportId, inlineResponse2004Reports.reportId) &&
        Objects.equals(this.reportStatus, inlineResponse2004Reports.reportStatus) &&
        Objects.equals(this.reportType, inlineResponse2004Reports.reportType) &&
        Objects.equals(this.reportExpiry, inlineResponse2004Reports.reportExpiry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportId, reportStatus, reportType, reportExpiry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("{\n");
    sb.append("    reportId: ").append(toIndentedString(reportId)).append("\n");
    sb.append("    reportStatus: ").append(toIndentedString(reportStatus)).append("\n");
    sb.append("    reportType: ").append(toIndentedString(reportType)).append("\n");
    sb.append("    reportExpiry: ").append(toIndentedString(reportExpiry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
