/*
 * Messaging API v3.1.0
 * Send and receive SMS & MMS programmatically, leveraging Australia's leading mobile network. With Telstra's Messaging API, we take out the complexity to allow seamless messaging integration into your app, with just a few lines of code. Our REST API is enterprise grade, allowing you to communicate with engaging SMS & MMS messaging in your web and mobile apps in near real-time on a global scale. 
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telstra;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * GetRecipientOptouts200Response
 */


public class GetRecipientOptouts200Response {
  @SerializedName("recipientOptouts")
  private List<RecipientOptout> recipientOptouts = null;

  @SerializedName("paging")
  private GetMessages200ResponsePaging paging = null;

  public GetRecipientOptouts200Response recipientOptouts(List<RecipientOptout> recipientOptouts) {
    this.recipientOptouts = recipientOptouts;
    return this;
  }

  public GetRecipientOptouts200Response addRecipientOptoutsItem(RecipientOptout recipientOptoutsItem) {
    if (this.recipientOptouts == null) {
      this.recipientOptouts = new ArrayList<RecipientOptout>();
    }
    this.recipientOptouts.add(recipientOptoutsItem);
    return this;
  }

   /**
   * The paginated results of your request. To fetch the next set of results, send another request and provide the succeeding offset value. 
   * @return recipientOptouts
  **/
  @Schema(description = "The paginated results of your request. To fetch the next set of results, send another request and provide the succeeding offset value. ")
  public List<RecipientOptout> getRecipientOptouts() {
    return recipientOptouts;
  }

  public void setRecipientOptouts(List<RecipientOptout> recipientOptouts) {
    this.recipientOptouts = recipientOptouts;
  }

  public GetRecipientOptouts200Response paging(GetMessages200ResponsePaging paging) {
    this.paging = paging;
    return this;
  }

   /**
   * Get paging
   * @return paging
  **/
  @Schema(description = "")
  public GetMessages200ResponsePaging getPaging() {
    return paging;
  }

  public void setPaging(GetMessages200ResponsePaging paging) {
    this.paging = paging;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetRecipientOptouts200Response inlineResponse2002 = (GetRecipientOptouts200Response) o;
    return Objects.equals(this.recipientOptouts, inlineResponse2002.recipientOptouts) &&
        Objects.equals(this.paging, inlineResponse2002.paging);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipientOptouts, paging);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("{\n");
    sb.append("    recipientOptouts: ").append(toIndentedString(recipientOptouts)).append("\n");
    sb.append("    paging: ").append(toIndentedString(paging)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
