/*
 * Messaging API v3.1.0
 * Send and receive SMS & MMS programmatically, leveraging Australia's leading mobile network. With Telstra's Messaging API, we take out the complexity to allow seamless messaging integration into your app, with just a few lines of code. Our REST API is enterprise grade, allowing you to communicate with engaging SMS & MMS messaging in your web and mobile apps in near real-time on a global scale. 
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telstra;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;
/**
 * GetReportId200Response
 */


public class GetReportId200Response {
  @SerializedName("reportId")
  private UUID reportId = null;

  @SerializedName("reportStatus")
  private String reportStatus = null;

  @SerializedName("reportUrl")
  private String reportUrl = null;

  public GetReportId200Response reportId(UUID reportId) {
    this.reportId = reportId;
    return this;
  }

   /**
   * The UUID assigned to your report. 
   * @return reportId
  **/
  @Schema(description = "The UUID assigned to your report. ")
  public UUID getReportId() {
    return reportId;
  }

  public void setReportId(UUID reportId) {
    this.reportId = reportId;
  }

  public GetReportId200Response reportStatus(String reportStatus) {
    this.reportStatus = reportStatus;
    return this;
  }

   /**
   * The status of the report. It will be either:        * **queued** – the report is in the queue for generation.        * **completed** – the report is ready for download.        * **failed** – the report failed to generate. Please try again. 
   * @return reportStatus
  **/
  @Schema(description = "The status of the report. It will be either:        * **queued** – the report is in the queue for generation.        * **completed** – the report is ready for download.        * **failed** – the report failed to generate. Please try again. ")
  public String getReportStatus() {
    return reportStatus;
  }

  public void setReportStatus(String reportStatus) {
    this.reportStatus = reportStatus;
  }

  public GetReportId200Response reportUrl(String reportUrl) {
    this.reportUrl = reportUrl;
    return this;
  }

   /**
   * Use this link to download your CSV file.
   * @return reportUrl
  **/
  @Schema(description = "Use this link to download your CSV file.")
  public String getReportUrl() {
    return reportUrl;
  }

  public void setReportUrl(String reportUrl) {
    this.reportUrl = reportUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetReportId200Response inlineResponse2005 = (GetReportId200Response) o;
    return Objects.equals(this.reportId, inlineResponse2005.reportId) &&
        Objects.equals(this.reportStatus, inlineResponse2005.reportStatus) &&
        Objects.equals(this.reportUrl, inlineResponse2005.reportUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportId, reportStatus, reportUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("{\n");
    sb.append("    reportId: ").append(toIndentedString(reportId)).append("\n");
    sb.append("    reportStatus: ").append(toIndentedString(reportStatus)).append("\n");
    sb.append("    reportUrl: ").append(toIndentedString(reportUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
