/*
 * Messaging API v3.1.0
 * Send and receive SMS & MMS programmatically, leveraging Australia's leading mobile network. With Telstra's Messaging API, we take out the complexity to allow seamless messaging integration into your app, with just a few lines of code. Our REST API is enterprise grade, allowing you to communicate with engaging SMS & MMS messaging in your web and mobile apps in near real-time on a global scale. 
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telstra;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * RecipientOptout
 */


public class RecipientOptout {
  @SerializedName("optoutNumber")
  private String optoutNumber = null;

  @SerializedName("createTimestamp")
  private OffsetDateTime createTimestamp = null;

  public RecipientOptout optoutNumber(String optoutNumber) {
    this.optoutNumber = optoutNumber;
    return this;
  }

   /**
   * The mobile number that sent the optout request.
   * @return optoutNumber
  **/
  @Schema(description = "The mobile number that sent the optout request.")
  public String getOptoutNumber() {
    return optoutNumber;
  }

  public void setOptoutNumber(String optoutNumber) {
    this.optoutNumber = optoutNumber;
  }

  public RecipientOptout createTimestamp(OffsetDateTime createTimestamp) {
    this.createTimestamp = createTimestamp;
    return this;
  }

   /**
   * The date and time we received the optout request.
   * @return createTimestamp
  **/
  @Schema(description = "The date and time we received the optout request.")
  public OffsetDateTime getCreateTimestamp() {
    return createTimestamp;
  }

  public void setCreateTimestamp(OffsetDateTime createTimestamp) {
    this.createTimestamp = createTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipientOptout recipientOptout = (RecipientOptout) o;
    return Objects.equals(this.optoutNumber, recipientOptout.optoutNumber) &&
        Objects.equals(this.createTimestamp, recipientOptout.createTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optoutNumber, createTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("{\n");
    sb.append("    optoutNumber: ").append(toIndentedString(optoutNumber)).append("\n");
    sb.append("    createTimestamp: ").append(toIndentedString(createTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
